name: Build, Test and Deploy backend

on:
    # opening a pull request to master and develop branch will be a trigger
    pull_request:
      branches:
        - develop
    # any code pushed to master and develop branch will also be a trigger
    push:
      branches:
        - develop

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: develop
    - name: Injecting environment vars
      run: |
        echo "${{ secrets.TEST_SECRETS }}" >> .env
    - name: Building Docker containers
      run: |
        docker-compose up -d --build
        docker-compose logs
    # - name: Running Tests inside Docker containers
    #   run: |
    #     docker-compose exec -T api pytest

  deploy:
    name: Deploying on EC2 via SSH
    if: ${{ github.event_name == 'push' }}
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: develop
    - name: Deploying Application with rsync over SSH to EC2
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SSH_EC2_IP }}
        REMOTE_USER: ${{ secrets.SSH_EC2_USER }}
        SOURCE: .
        TARGET: ${{ github.event.repository.name }}
        SCRIPT_AFTER: |
          cd ~
          cd ${{ github.event.repository.name }}
          docker compose up -d --build
    # - name: Running Script via SSH on EC2
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SSH_EC2_IP }}
    #     username: ${{ secrets.SSH_EC2_USER }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script: |
    #       cd ~
    #       cd ${{ github.event.repository.name }}
    #       source ./docker-ec2-deploy.sh
